node-gh/gh

lib/cmd.js

`.some` always return `true` if **true** was found, otherwise: `false` will be returned.
:beers:

Using .some instead of .every in `hasCommandInOptions`

---

lib/cmds/repo.js

The issue is that the github library uses "organization" and not "org".

Fix issue where forking to an organization would not work.

---

lib/cmds/issue.js
lib/cmds/templates/issue.handlebars

This pull request add the next features:

Read and update more info from/to issues

---

index.html

Apparently the ascii.io domain is no longer on air, so we'll replace by asciinema.org which is the same service.

Replace ascii.io by asciinema.org

---

package.json

Change license string in `package.json` to silence warning
in latest `npm`

spdx-compliant license string

---

.travis.yml

See http://docs.travis-ci.com/user/migrating-from-legacy/
Basically, it appears that all is needed is to add `sudo: false` to `.travis.yml`. I'll submit a PR after I have given it a try to see if there's any issue with the current setup.

Travis-CI: Migrate from legacy infrastructure to container-based infrastructure

---

lib/cmd.js
lib/cmds/repo.js

This is a small first step toward making #357 a reality. This starts off by adding isTTY to the options so that commands may print or not some output based on the fact that the content is going to be piped out or not.
Initial implementation of repository listing for piping purposes.
Add a isTTY value on the options to determine whether or not the command is executed in a TTY context or not. Based on this value, output may be printed or not.
Set the default options.type based on whether we're listing a user or an organization repositories.

Limit repository listing output based on stdout.isTTY

---

lib/cmds/help.js

I assume this is meant to say `gh help -a` instead of `git help -a`

Fixes error in usage text

---

README.md
lib/cmds/issue.js

Adds the ability to search issues, including using github filters like `updated:<=2013-05-24`.
Here are the options and examples for the command.
Option             | Usage        | Type
---                | ---          | ---
`-s`, `--search`   | **Required** | `Boolean`
`-a`, `--all`      | *Optional*   | `Boolean`
`-d`, `--detailed` | *Optional*   | `Boolean`
`-r`, `--repo`     | *Optional*   | `String`
`-u`, `--user`     | *Optional*   | `String`
* Search issues in current repository
```
gh is --search 'term'
```
* Search issues in all repositories for a user
```
gh is --all --user node-gh --search 'term'
```
* Search issues in a repository for a user
```
gh is  --user node-gh --repo gh --search 'term'
```
* Search issues in a repository for a user with link and content
```
gh is …
```

Add the ability to search issues

---

lib/git.js

@dustinryerson reported a crash issue due to too many tags on a given code review program.
By default, `git pull` and `git fetch` fetches tags when invoked.
Too many objects (be it content, commits, tags, or whatever) on a git repository is problematic.

Don't pull tags on fetching remote branch.

---

lib/cmds/issue.js
lib/cmds/pull-request.js

The `--link` option is similar to `--detailed` except that it won't display the body of the issues.
Personally, I'm interested in this because I use iTerm, and it allows urls printed to the terminal to be clicked and open in my browser.
As a side note, I think it would be really amazing to introduce a feature like git's `--pretty=format`

adds --link option that prints links to issues and pull requests

---

README.md

The README for this project has a ton of syntax errors, so the rendered result
on Github itself is ugly and confusing! This simple update fixes most of them.

Fix markdown codeblock syntax so the README renders as intended

---

.travis.yml

Looks like CI on master branch has issue with color display, maybe we could force enable it to prevent the test failed.

Set FORCE_COLOR=true as environment variable on Travis CI

---

lib/hooks.js

First of all, let me start by saying great job on Node GH!
It's a real lifesaver for me and my team!
I've noticed a small bug though:
When the `--no-hooks` flag is given, Node-GH sometimes resolves in an error.
For example:
`gh pr 1 --no-hooks --fetch --merge --branch my-branch`
Will result in:
```
TypeError: afterHooksCallback is not a function
at /Users/jeffrey/.nvm/versions/node/v8.9.4/lib/node_modules/gh/lib/cmds/pull-request.js:868:13
at /Users/jeffrey/.nvm/versions/node/v8.9.4/lib/node_modules/gh/lib/cmds/pull-request.js:346:9
at /Users/jeffrey/.nvm/versions/node/v8.9.4/lib/node_modules/gh/node_modules/github/api/v3.0.0/pullRequests.js:118:17
at callCallback (/Users/jeffrey/.nvm/versions/node/v8.9.4/lib/node_modules/gh/node_modules/github/index.js:743:17)
at …
```

Fixes errors happening when '--no-hooks' was given.

---

README.md

Not obvious that pathPrefix is required to support GHE.

Improve docs for github enterprise

---

README.md
lib/logger.js
package-lock.json
test/logger.js

This PR simply adds a `--no-color` flag to each command that typically outputs color'd output as mentioned in #544. This will result in the output having no colors at all.

Add --no-color flag to commands

---

lib/cmds/issue.js

fixes #540.  There was a bug in the `labels` var assignment in cmds/issue.js , from the nonexistent attribute `issue.label`, fixed with `issue.labels`.  Further down, the `labels` array was pushed to from iterating on itself with `label.name`, rather than making a fresh array of label strings for display.  Finally, made a distinctive color for issue display and displayed the appropriate singular/plural of 'label'.

fixed display of labels (they hadn’t been displaying)

---

lib/cmds/pull-request.js
lib/hooks.js
lib/rest-api-client.js
test/pull-request.js

I'm working on a set of changes where the branches are prefixed with `gdpr-*`, and whenever I try to submit a PR with one of these branches, I get the following error:
```
error: src refspec pr-gdLPS-84401-roles-uad does not match any.
error: failed to push some refs to 'git@github.com:drewbrokke/liferay-portal-ee.git'
/usr/local/lib/node_modules/gh/lib/exec.js:53
throw err
^
Error: Child process terminated with error code 1
at Object.exports.spawnSyncStream (/usr/local/lib/node_modules/gh/lib/exec.js:49:15)
at Object.exports.push (/usr/local/lib/node_modules/gh/lib/git.js:62:17)
at /usr/local/lib/node_modules/gh/lib/cmds/pull-request.js:770:17
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:718:13
at iterate (/usr/local/lib/node_modules/gh/node_modules/async/lib/async.js …
```

GH attempts to link a PR to the wrong remote branch name when the local branch name contains 'pr-'

---

.vscode/launch.json
README.md
default.gh.json
src/cmds/issue.ts
src/cmds/pull-request.ts

Adding `"use_editor": false` to `~/.gh.json` will now not open editor for messages.
For PRs with this setting off, title will be computed from the last commit msg.

Add config to turn off open editor feature

---

package-lock.json
package.json

Fix `Error: ENOENT: no such file or directory` upon initial install.

fix(json): add default.gh.json to npm published files

---

README.md
package-lock.json
src/utils.ts

To determine which editor to use for commit messages
look if $EDITOR or $VISUAL are set in the environment
before checking the git config. If no editor is found
throw an error. Fixes #745

fix: check for editor in environment variables
