node-gh/gh

README.md
default.gh.json
lib/base.js

more details in https://github.com/mikedeboer/node-github/pull/106

github enterprise may require a pathPrefix options

---

lib/cmds/issue.js

```
/usr/local/lib/node_modules/gh/lib/cmds/issue.js:370
labels.forEach(function(label) {
^
TypeError: Cannot read property 'forEach' of undefined
at /usr/local/lib/node_modules/gh/lib/cmds/issue.js:370:27
at Array.forEach (native)
at /usr/local/lib/node_modules/gh/lib/cmds/issue.js:359:20
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:708:13
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:49:16
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:263:32
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:40:16
at /usr/local/lib/node_modules/gh/node_modules/async/lib/async.js:705:17
at /usr/local/lib/node_modules/gh/node_modules/github/api/v3.0.0/issues.js:127:17
at callCallback …
```

solve problem from issues without labels

---

README.md

Update supported node version >= 0.12 on README

---

lib/cmds/milestone.js

Related to, but does not address #346.

Added basic read support for milestones

---

lib/cmds/issue.js

https://github.com/node-gh/gh/issues/429

Fix #429 Created At Date is Incorrect

---

lib/configs.js

This will fix https://github.com/node-gh/gh-travis/issues/13

Fix Node v6.x symlink resolve behaviour to make plugins work

---

lib/cmds/gists.js
lib/cmds/issue.js
lib/cmds/pull-request.js
lib/cmds/repo.js
lib/configs.js
lib/logger.js

Support github enterprise urls from config

---

README.md
lib/cmds/issue.js

This is an update for https://github.com/node-gh/gh/issues/358.

Adding support for assigning issues to other users (#358)

---

README.md
lib/cmds/repo.js

This is an update for https://github.com/node-gh/gh/issues/397.

Add clone repo support

---

README.md
lib/cmds/repo.js

This is an update for https://github.com/node-gh/gh/issues/448.

Add label configuration support

---

lib/base.js

This does this for repo functions. I imagine that this can be easily updated to work for more situations. Aims to resolve #539 
I accept that this might need extending, but I am not sure how best to do that.

Add pagination

---

lib/cmds/pull-request.js

@protoEvangelion Take a look at this fix. Seems noticed that if a branch is not found, the error log prints with "Undefined" as the message. Threw in an extra catch to check for message being available or not. I wasn't familiar with the other error cases and if/when the errors[0].message actually returns something.
Let me know if you have questions
fix #567

fix(pull-request.js): Update pull request send error handling

---

lib/cmds/pull-request.js

refactor(pull-request.js): simplify the error handling logic as much as possible

---

README.md

correct bad anchor link in TOC, make header words case consistent

Minor TOC fixes

---

.github/ISSUE_TEMPLATE/bug_report.md

request version number in bug report template

---

.vscode/launch.json
CONTRIBUTING.md
__tests__/user.test.ts
package-lock.json
package.json
src/base.ts
src/cmd.ts
src/cmds/alias.ts
src/cmds/gists.ts
src/cmds/hello.ts
src/cmds/help.ts
src/cmds/issue.ts
src/cmds/milestone.ts
src/cmds/notification.ts
src/cmds/pull-request.ts
src/cmds/repo.ts
src/cmds/user.ts
src/cmds/version.ts
src/git.ts
src/github.ts
src/utils.ts
tsconfig.json

Treat options as immutable with [immer](https://immerjs.github.io/immer/docs/introduction) and remove prototype & this references.

Remove OOP style to prepare the way for FP

---

package-lock.json
package.json

build(package.json): add ramda as new dependency

---

__mocks__/tmp.js
package-lock.json
package.json
src/utils.ts

This uses the OS's standard temp dir which should resolve permission issues.

Fix permission issue for opening a temp file in user's editor

---

package-lock.json
package.json

fix(options): update nock to fix swallowed options

---

README.md
src/cmds/repo.ts

Simplifies creating a new repo and cloning into current dir.
```
gh re --new --clone --init
```

feat(repo): create new repo based on directory name and clone
